### Project specific config ###
language: objective-c
node_js:
  - node

env:
  global:
    - ATOM_LINT_WITH_BUNDLED_NODE=true

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 20

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
